### ISSUE TITLE
複数人がObjectをEquipしているとLate-JoinerはEquipしてないようにみえる

### ISSUE THREAD

**Issue by anonaisu** [mimyquality/FukuroUdon#13]
以下報告します。ご確認いただけると幸いです。

■不具合
　Ver 1.15.1、および 1.13.2
　PlayerAにObjectAをEquip、PlayerBにObjectBをEquipさせた後、Late-Joiner(PlayerC)はPlayerAにObjectAがEquip、PlayerBはObjectBがEquipされずObjectBが座標(x:0, y:0, z:0)に配置される

■正常
　Ver 1.12.3
　PlayerAにObjectAをEquip、PlayerBにObjectBをEquipさせた後、Late-Joiner(PlayerC)はPlayerAにObjectAがEquip、PlayerBにObjectBがEquip

**Comment by mimyquality** [comment]
PlayerAとPlayerBの差は何がありますか？(PlayerAがインスタンスマスターである、等)

また、ObjectA, ObjectBはワールドのロード時点で非アクティブ、もしくはVRC Object Poolに登録されたオブジェクトですか？

**Comment by anonaisu** [comment]
PlayerAがインスタンスマスターです。

ObjectA、ObjectBともにロード時点でアクティブです。VRC Object Poolは使っていません。

　※1.13.0にOwner権が移譲された際、Equipが強制的に外れるようになりましたが、もしかするとそれが影響しているかと思いました。

**Comment by mimyquality** [comment]
こちらでも再現しました。
ver 1.16.3にて対策しましたのでご確認ください。

**Comment by anonaisu** [comment]
ver 1.16.3で正常動作することを確認できました。
早急のご対応ありがとうございました。
