### ISSUE TITLE
他PlayerがPickUpができなくなる現象

### ISSUE THREAD

**Issue by anonaisu** [mimyquality/FukuroUdon#14]
Manual Object Syncで以下の現象が発生しました。ご確認いただけると幸いです。

■不具合
　ver 1.16.3
　PlayerAがObjecAをPickUp→ObjectAをDetach→ObjectAをDrop→ObjectAをAttach
　を行うとPlayerBがObjectAをPickUpできなくなる。

■正常
　ver 1.12.1、1.15.1
　PlayerAがObjecAをPickUp→ObjectAをDetach→ObjectAをDrop→ObjectAをAttach
　を行ってもPlayerBがObjectAをPickUpを可能。

なお、ver1.16.3であったとしてもVRC PickUpのDisallow TheftのチェックボックスをOffにすると正常動作します。
PlayerAがOwnerでしたがPlayerBがPickUpしてもPlayerAがPickUpできなくなります。ObjectAはアクティブでVRC Object Poolは使っていません。

**Comment by mimyquality** [comment]
こちら ver 1.16.4 で修正しました。

**Comment by anonaisu** [comment]
ver 1.16.4にて修正され正常動作するのを確認いたしました。
早急のご対応ありがとうございました。
