### ISSUE TITLE
ObjectをPickupしているPlayerがLeftしたら残りのプレーヤーにObjectがAttachされる。

### ISSUE THREAD

**Issue by anonaisu** [mimyquality/FukuroUdon#16]
Manual Object Syncで以下の現象が発生しました。ご確認いただけると幸いです。

Playerが３人いる状態で不具合を確認しました。
ObjectをPickupしているPlayerAがLeftしたら、PlayerBにObjectがAttachされてしまうことをPlayerCから確認されました。PlayerBからはAttachされているようには見えません。

Unity 2022.3.22f1
VRCSDK 3.7.1
FukuroUdon 2.0.1

**Comment by mimyquality** [comment]
症状確認しました。
正確には、インスタンスマスターがピックアップしたままLeaveすると、次のインスタンスマスターがピックアップしているように見える(次のインスタンスマスター自身は正常)
と言う状態ですね。修正します。

**Comment by mimyquality** [comment]
Fukuro Udon 3.0.1 で修正しました。

**Comment by anonaisu** [comment]
修正されたことを確認いたしました。ありがとうございます。

ただ一点、ObjectにつけたVRC PickupのComponentのDisallow TheftをチェックOnした場合、このObjectをPickupしたPlayerAがLeftすると残りのPlayerBがこのObjectをPickupできない事象を確認しました。Disallow TheftをチェックOffにした場合はこの事象は起きませんでした。ご確認いただけると幸いです。

**Comment by mimyquality** [comment]
Fukuro Udon 3.0.2 で Disallow Theft の問題にも対処しました。
もう問題は起きないはずです。

**Comment by anonaisu** [comment]
問題が発生しないことを確認しました。
早急のご対応ありがとうございました。
