### ISSUE TITLE
ManualObjectSyncを持っていなくても毎フレームPostLateUpdateを発火しています

### ISSUE THREAD

**Issue by bdunderscore** [mimyquality/FukuroUdon#4]
ManualObjectSyncにPostLateUpdateのイベントがあるので、毎フレーム負荷を発生しています。オブジェクトの数が多いとこのようにかなりの負荷になるようです。

![image](https://github.com/mimyquality/FukuroUdon/assets/64174065/7875b6cd-6bdf-43b2-b8d0-43d63df0ae35)

**Comment by mimyquality** [comment]
PostLateUpdate()はアバターのボーン座標を参照する必要性から、別案を採るのが難しいですね
試しにUpdate()に変えてみたら、ちょっとなんとも言えない結果になりましたが…

PostLateUpdate()
![image](https://github.com/mimyquality/FukuroUdon/assets/86596687/ea8decd9-7101-4dbb-8911-5aa40fdd9460)

Update()
![image](https://github.com/mimyquality/FukuroUdon/assets/86596687/fa58b9e8-8c33-45d5-bd88-c36228004c54)

**Comment by bdunderscore** [comment]
問題なのは、そもそも動いてない・手に持ってないオブジェクトまでPostLateUpdateの負荷がかかるというところです。持っているものがPostLateUpdateで起動してしまうのは仕方ないですが、PostLateUpdateの処理を別コンポーネントに移動させることで必要な時だけ有効にできます（Attach-To-Meがこの方式です）

この際、その付属コンポーネントを自動的に追加するエディタ拡張があるのが望ましいでしょう。

**Comment by mimyquality** [comment]
ver 1.6.0 で対応しました。
Attach-To-Meも参考になりました。ありがとうございます。
