### ISSUE TITLE
オブジェクトをEquipしたPlayerがLeftすると、他プレーヤがそのオブジェクトをEquipしてしまう。

### ISSUE THREAD

**Issue by anonaisu** [mimyquality/FukuroUdon#9]
PlayerAがObjectをEquipし、EquipしたままInstanceをLeftすると、Instanceに残っているPlayerBがObjectをEquipします。

使用したスクリプトは以下です。

    ManualObjectSync _object

    public override void Interact()
    {
        VRCPlayerApi lp = Networking.LocalPlayer;
        Networking.SetOwner(lp, _sync.gameObject);
       _object.Equip(HumanBodyBones.Head);       
    }

**Comment by anonaisu** [comment]
以下のスクリプト追記で回避可能でした。
   
    public override void OnPlayerLeft(VRCPlayerApi player)
    {
        if (_sync.IsEquiped) { _sync.Unequip(); }
    }

**Comment by mimyquality** [comment]
ver 1.12.4 にて対応しました

**Comment by anonaisu** [comment]
1.12.4にUpdate後でも掲題と同じ現象が発生しました。
こちらの環境がわるいかもしれませんのでもう少し調べてみます。
早急のご対応ありがとうございます。

**Comment by mimyquality** [comment]
現行の仕様上、退室したのがOwnerか判定が難しかったため、オーナーが切り替わると強制的にEquipを解除するようにしました。

**Comment by anonaisu** [comment]
1.13.0にUpdate後、現象が解消されました。
ご対応ありがとうございました。
